#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../Program Files (x86)/NAG/FBuilder 7.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -O4
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -O4 -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../Program Files (x86)/NAG/FBuilder 7.1/lib64' -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = 201611_Japan_maritime.exe

#Target name
NI_TARGET = 201611_Japan_maritime.exe

#Object files
NI_OBJS =	 \
	NW_INFO.o \
	NW_SIZE.o \
	derase.o \
	main.o \
	mar_all_not.o \
	mar_main.o \
	mar_sub.o

#Depend Object files
NI_DOBJS =	 \
	NW_INFO.o \
	NW_SIZE.o \
	derase.o \
	main.o \
	mar_all_not.o \
	mar_main.o \
	mar_sub.o

#Prospective Module files
NI_MODS =	 \
    'nw_info.mod' \
    'nw_size.mod'

#Fortran Information files
NI_FIFS =	 \
	NW_INFO.fif \
	NW_SIZE.fif \
	derase.fif \
	main.fif \
	mar_all_not.fif \
	mar_main.fif \
	mar_sub.fif

#Library files
NI_LIBS = 

#Dependencies
NI_EQ==
NI_SC=\;
NW_INFO.o:	NW_INFO.f90
nw_info.mod:	NW_INFO.f90
NW_SIZE.o:	NW_SIZE.f90
nw_size.mod:	NW_SIZE.f90
derase.o:	derase.f90
main.o:	main.f90
main.o:	nw_info.mod
main.o:	nw_size.mod
mar_all_not.o:	mar_all_not.f90
mar_all_not.o:	nw_info.mod
mar_main.o:	mar_main.f90
mar_main.o:	nw_info.mod
mar_main.o:	nw_size.mod
mar_sub.o:	mar_sub.f90
mar_sub.o:	nw_info.mod

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'201611_Japan_maritime.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
NW_INFO.o nw_info.mod:
	@echo @nagfor NW_INFO.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) NW_INFO.fif -c NW_INFO.f90
NW_SIZE.o nw_size.mod:
	@echo @nagfor NW_SIZE.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) NW_SIZE.fif -c NW_SIZE.f90
derase.o:
	@echo @nagfor derase.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) derase.fif -c derase.f90
main.o:
	@echo @nagfor main.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) main.fif -c main.f90
mar_all_not.o:
	@echo @nagfor mar_all_not.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) mar_all_not.fif -c mar_all_not.f90
mar_main.o:
	@echo @nagfor mar_main.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) mar_main.fif -c mar_main.f90
mar_sub.o:
	@echo @nagfor mar_sub.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) mar_sub.fif -c mar_sub.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'201611_Japan_maritime.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) NW_INFO.o NW_SIZE.o derase.o main.o mar_all_not.o mar_main.o mar_sub.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) NW_INFO.fif NW_SIZE.fif derase.fif main.fif mar_all_not.fif mar_main.fif mar_sub.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
